# Generated by Django 5.2.5 on 2025-08-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Father', models.CharField(max_length=30)),
                ('GrandFather', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=20)),
                ('MaritalStatus', models.CharField(max_length=20)),
                ('MatricResult', models.IntegerField()),
                ('DateOfBirth', models.DateField()),
                ('Age', models.IntegerField()),
                ('PlaceOfBirth', models.CharField(max_length=30)),
                ('Photo', models.ImageField(upload_to='')),
                ('Nationality', models.CharField(max_length=20)),
                ('Region', models.CharField(max_length=30)),
                ('Disability', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.IntegerField()),
                ('Password', models.CharField(max_length=20, unique=True)),
                ('IdentityCard', models.CharField(max_length=20)),
                ('No', models.IntegerField()),
            ],
        ),
    ]
