# Generated by Django 5.2.4 on 2025-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_informations',
            name='Password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_informations',
            name='Photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
